arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - base_joint
     - shoulder_joint
     - elbow_joint
     - wrist_pitch_joint
     - wrist_roll_joint
  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    base_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    shoulder_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    elbow_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    wrist_pitch_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    wrist_roll_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
  gains:
    base_joint: {p: 10000.0, i: 1.0, d: 10.0}
    shoulder_joint: {p: 10000.0, i: 1.0, d: 10.0}
    elbow_joint: {p: 10000.0, i: 1.0, d: 10.0}
    wrist_pitch_joint: {p: 10000.0, i: 1.0, d: 10.0}
    wrist_roll_joint: {p: 10000.0, i: 1.0, d: 10.0}
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - gripper_joint
     - sub_gripper_joint
  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    gripper_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
    sub_gripper_joint:
      trajectory: 1.0               # Not enforced if unspecified
      goal: 0.5                     # Not enforced if unspecified
  gains:
    gripper_joint: {p: 100.0, i: 1, d: 0.1}
    sub_gripper_joint: {p: 100.0,  i: 1, d: 0.1}